sudo: false
language: node_js
node_js:
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
osx_image: xcode8.2

before_install:
  - brew update
  - brew outdated graphicsmagick || brew upgrade graphicsmagick
